### ISSUE TITLE
Cannot read property 'findOneAndUpdate' of undefined

### ISSUE THREAD

**Issue by mumup** [JasonBoy/wechat-jssdk#44]
系统：Ubuntu 18.04.3 x64
Node：v12.14.1
MongoDB: 4.0.3 (升级至4.2.2一样

只用了小程序的功能

```javascript
const { Wechat, MongoStore } = require('wechat-jssdk')

// =========> TypeError: Cannot read property 'findOneAndUpdate' of undefined <==========
const mongoStore = new MongoStore({
  dbHost: process.env.DB_HOST,
  dbPort: process.env.DB_PORT,
  dbName: 'cat',
  dbOptions: {
    user: process.env.DB_USER,
    pass: process.env.DB_PASS,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true
  }, // extra options passed to mongoose
  limit: 10 // how many url signature and oauth token items should be initialized from db, default: 20
})

const wechatConfig = {
  appId: process.env.APP_ID,
  appSecret: process.env.APP_SECRET,
  // 小程序配置
  miniProgram: {
    appId: process.env.APP_ID,
    appSecret: process.env.APP_SECRET
  },
  store: mongoStore
}
const wx = new Wechat(wechatConfig)

module.exports = wx
```

### 报错文字
```
/home/nodejs-web/mpi-miniprogram/node_modules/wechat-jssdk/lib/store/MongoStore.js:350
      return this.GlobalToken.findOneAndUpdate({}, Object.assign({}, gt), {
                              ^

TypeError: Cannot read property 'findOneAndUpdate' of undefined
    at MongoStore.flushGlobalToken (/home/nodejs-web/mpi-miniprogram/node_modules/wechat-jssdk/lib/store/MongoStore.js:350:31)
    at MongoStore.flush (/home/nodejs-web/mpi-miniprogram/node_modules/wechat-jssdk/lib/store/MongoStore.js:473:12)
    at Timeout._onTimeout (/home/nodejs-web/mpi-miniprogram/node_modules/wechat-jssdk/lib/store/Store.js:100:47)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

```

**Comment by JasonBoy** [comment]
`Mongodb connected` 确认db连接上了么？

**Comment by mumup** [comment]
没连上，打扰了
